/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Dav(props) {
  const { nodes, materials } = useGLTF("/3D CREVILLENTE.gltf");
  return (
    <group {...props} dispose={null}>
      <group position={[0.24, 0.14, -0.11]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["_3D---ARCHIVADOR_GRANDE_ARD-geom"].geometry}
          material={materials["_3D---ARCHIVADOR_GRANDE_ARD_front"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["_3D---ARCHIVADOR_GRANDE_ARD-geom_1"].geometry}
          material={materials["_3D---ARCHIVADOR_GRANDE_ARD_back"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["_3D---ARCHIVADOR_GRANDE_ARD-geom_2"].geometry}
          material={materials["_3D---ARCHIVADOR_GRANDE_ARD_edge"]}
        />
      </group>
      <group position={[-0.1, 0.18, 0.24]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["_3D---ARCHIVADOR_GRANDE_ARD-geom001"].geometry}
          material={materials["_3D---ARCHIVADOR_GRANDE_ARD_front.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["_3D---ARCHIVADOR_GRANDE_ARD-geom001_1"].geometry}
          material={materials["back-dil"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["_3D---ARCHIVADOR_GRANDE_ARD-geom001_2"].geometry}
          material={materials["_3D---ARCHIVADOR_GRANDE_ARD_edge.001"]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/3D CREVILLENTE.gltf");
